services:
  app:
    container_name: reelgenius-backend
    hostname: app
    build: .
    volumes:
      - ./data:/app/data
      - ./output:/app/output
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - STABILITY_API_KEY=${STABILITY_API_KEY}
      - PLATFORM=${PLATFORM:-tiktok}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING:-false}
      - LANGSMITH_ENDPOINT=${LANGSMITH_ENDPOINT:-https://eu.api.smith.langchain.com}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}
      # Redis configuration
      - REDIS_URL=redis://redis:6379/0
      # PostgreSQL configuration
      - DATABASE_URL=postgresql://reelgenius:reelgenius@postgres:5432/videogen
    ports:
      - "8000:8000"
    networks:
      - reelgenius-network
    depends_on:
      - redis
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      
  ui:
    container_name: reelgenius-frontend
    hostname: ui
    build: ./ui/reel_genius
    environment:
      - NEXT_PUBLIC_API_URL=http://app:8000 
      - DOCKER_ENV=true
      - NODE_ENV=production
      - NEXT_PUBLIC_DEBUG=true
    ports:
      - "3000:3000"
    networks:
      - reelgenius-network
    depends_on:
      app:
        condition: service_healthy
    # Add a startup command to test connectivity
    entrypoint: >
      sh -c "
        echo 'Testing connectivity before starting the UI...' &&
        ./docker-test-connectivity.sh &&
        npm start
      "

  worker:
    container_name: reelgenius-worker
    hostname: worker
    build: .
    command: celery -A video_generator.tasks worker --loglevel=info
    volumes:
      - ./data:/app/data
      - ./output:/app/output
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - STABILITY_API_KEY=${STABILITY_API_KEY}
      - PLATFORM=${PLATFORM:-tiktok}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING:-false}
      - LANGSMITH_ENDPOINT=${LANGSMITH_ENDPOINT:-https://eu.api.smith.langchain.com}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}
      # Redis configuration
      - REDIS_URL=redis://redis:6379/0
      # PostgreSQL configuration
      - DATABASE_URL=postgresql://reelgenius:reelgenius@postgres:5432/videogen
    networks:
      - reelgenius-network
    depends_on:
      - redis
      - postgres

  redis:
    container_name: reelgenius-redis
    hostname: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - reelgenius-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    container_name: reelgenius-postgres
    hostname: postgres
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=reelgenius
      - POSTGRES_PASSWORD=reelgenius
      - POSTGRES_DB=videogen
    networks:
      - reelgenius-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reelgenius -d videogen"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  reelgenius-network:
    driver: bridge